{
 "title": "Week 5 Homework",
 "time": { "from": "2023-02-28T20:10:35.000Z", "to": "2023-03-30T19:44:39.000Z" },
 "panels": [
  {
   "title": "Prefiction drift",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Fare_amount Quantile",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT column_quantile, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share of Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}